/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  api: {
    v1: {
      DynamicQris: () => import('#controllers/api/v1/dynamic_qris_controller'),
      StaticQris: () => import('#controllers/api/v1/static_qris_controller'),
    },
  },
  Dashboard: () => import('#controllers/dashboard_controller'),
  DynamicQris: () => import('#controllers/dynamic_qris_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Qris: () => import('#controllers/qris_controller'),
  Roles: () => import('#controllers/roles_controller'),
  Session: () => import('#controllers/session_controller'),
  Users: () => import('#controllers/users_controller'),
  WebhookSettings: () => import('#controllers/webhook_settings_controller'),
  Documentations: () => import('#controllers/documentations_controller'),
}
