/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  NewAccount: () => import('#controllers/new_account_controller'),
  Session: () => import('#controllers/session_controller'),
  Roles: () => import('#controllers/roles_controller'),
  Users: () => import('#controllers/users_controller'),
  Qris: () => import('#controllers/qris_controller'),
  Profile: () => import('#controllers/profile_controller'),
  DynamicQris: () => import('#controllers/dynamic_qris_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
}
